#!/usr/bin/env bash
# Script that
#	Creates the file '/var/run/myscript.pid' containing its PID
#	Displays 'To infinity and beyond' indefinitely
#	Displays 'I hate the kill command' when receiving a SIGTERM signal
#	Displays 'Y U no love me?!' when receiving a SIGINT signal
#	Deletes the file '/var/run/myscript.pid' and terminates itself when receiving a SIGQUIT or SIGTERM signal

remove_and_quit() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" >> /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" && remove_and_quit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'remove_and_quit' SIGQUIT
done
