#!/usr/bin/env bash
# This script is used to kill another process

for pid in /proc/[0-9]*
do
	proc_name=$(cat $pid/cmdline | tr '\0' ' ')
	if [[ $proc_name == *"4-to_infinity_and_beyond"* ]]
	then
		kill -15 $(basename $pid)
	fi
done
