#!/usr/bin/env bash
# This script displays 
#	'To infinity and beyond' indefinitely
#	With a 'sleep 2' in between each iteration
#	'I am invincible!!!' when receiving a 'SIGTERM' signal

while true
do
	echo "To infinity and beyond"
	sleep 2s
	trap "echo 'I am invincible!!!'" SIGTERM
done
