#!/usr/bin/env bash
# This script select 'username', 'user id', 'home directory' from /etc/passwd output

while read -r line
do
	username=$(echo "$line" | cut -d: -f1)
	userid=$(echo "$line" | cut -d: -f3)
	homedir=$(echo "$line" | cut -d: -f6)
	echo "$username:$userid:$homedir"
done < "/etc/passwd"

