#!/usr/bin/env bash
# This script displays numbers from 1 to 10 and 'Hi' if the number is 9

i=1
while [ "$i" -le 10 ]
do
	echo "Best School"
	if [ "$i" -eq 9 ]
	then
		echo "Hi"
	fi
	i=$((i + 1))
done
