#!/usr/bin/env bash
# This script displays 'bad luck', 'good luck', 'Best School' on conditions

i=1
while [ "$i" -le 10 ]
do
	if [ "$i" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
