#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minuts

hour=0
while [ "$hour" -le 12 ]
do
	echo "Hour: $hour"
	(( minut=1 ))
	while [ "$minut" -le 59 ]
	do
		echo "$minut"
		minut=$((minut + 1 ))
	done
	hour=$((hour + 1))
done
